enum ERROR_CODES {
  NOT_SPECIFIED = "NOT_SPECIFIED",
  INVALID_URL = "INVALID_URL",
  INVALID_ADDRESS = "INVALID_ADDRESS",
  FAILD_TO_GET_ANALYSIS = "FAILD_TO_GET_ANALYSIS",
  ANALYSIS_LAST_TO_LATE = "ANALYSIS_LAST_TO_LATE",
}

export default ERROR_CODES;
