enum ERROR_CODES {
  NOT_SPECIFIED = "NOT_SPECIFIED",
  INVALID_URL = "INVALID_URL",
  FAILED_TO_GET_ANALYSIS = "FAILED_TO_GET_ANALYSIS",
  ANALYSIS_LAST_TO_LATE = "ANALYSIS_LAST_TO_LATE",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export default ERROR_CODES;
